server:
  port: 12800

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gateway?serverZoneId=Asia/Shanghai
    username: root
    password: 123456
    pool:
      initial-size: 20
      max-size: 50
  jpa:
    show-sql: true

